version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: chat_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Adjust as per your Elasticsearch requirements
    ports:
      - "9200:9200"  # Expose Elasticsearch HTTP port
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"  # Expose Redis port
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Specify your Rails Dockerfile
    command: bash -c "bin/rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - elasticsearch
    environment:
      RAILS_ENV: development  # Set your Rails environment
      DATABASE_URL: mysql2://root:password@db:3306/chat_system  # Adjust database connection URL
      ELASTICSEARCH_URL: http://elasticsearch:9200  # Adjust Elasticsearch URL

    ports:
      - "3000:3000"       
volumes:
  my-db:
